LabJournal/urls.py
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('viscosimeters.urls')),
    path('attestationJ/kinematicviscosity/', include('kinematicviscosity.urls')),
    path('attestationJ/dinamicviscosity/', include('dinamicviscosity.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
    path('equipment/', include('equipment.urls')),
    path('CertifiedValueJ/', include('jouViscosity.urls')),
    path('CertifiedValueJ/', include('jouChlorineOilProducts.urls')),
    # path('CertifiedValueJ/', include('jouPetroleumChlorineImpurityWater.urls')),
    # path('CertifiedValueJ/', include('jougascondensate.urls')),
    path('attestationJ/clorinesalts/', include('clorinesalts.urls')),
    path('productionJ/clorinesaltsprod/', include('clorinesaltsprod.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.TOOLBAR_DEBUG:
    import debug_toolbar

    import mimetypes

    mimetypes.add_type("application/javascript", ".js", True)

    urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('ViscosimeterTypeAPI/', views.ViscosimeterTypeListCreateApiView.as_view()),
]

viscosimeters/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('viscosimeterskonstants/', views.ViscosimetersView.as_view(), name='konstv'),
    path('kalibrationviscosimetersreg/', views.KalibrationViscosimetersRegView, name='kalibrationviscosimetersreg'),
    path('viscosimeters/', views.ViscosimetersHeadView.as_view(), name='vt'),
]

viscosimeters/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from equipment.models import Manufacturer, Equipment, MeasurEquipment
from django.db.models import Subquery

class ViscosimeterType(models.Model):
    pairNumber = models.CharField('Номер пары', max_length=100)
    diameter = models.CharField('Диаметр', max_length=5, unique=True)
    viscosity1000 = models.CharField('Вязкость за 1000 сек, сСт', max_length=30)
    range = models.CharField('Область измерений, сСт', max_length=30)

    def __str__(self):
        return f'{self.diameter}'

    class Meta:
        verbose_name = 'Тип вискозиметра'
        verbose_name_plural = 'Типы вискозиметров'


class Viscosimeters(models.Model):
    viscosimeterType = models.ForeignKey(ViscosimeterType, verbose_name='Диаметр',
                                         on_delete=models.PROTECT)
    equipmentSM = models.ForeignKey(MeasurEquipment, verbose_name='СИ',
                                    on_delete=models.PROTECT, related_name='equipmentSM', blank=True, null=True,
                                    )

    def __str__(self):
        return f'№ {self.equipmentSM.equipment.lot} ({self.viscosimeterType.viscosity1000} сСт)'

    def get_absolute_url(self):
        """ Создание юрл объекта для перенаправления из вьюшки создания объекта на страничку с созданным объектом """
        return reverse('Str', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Вискозиметр'
        verbose_name_plural = 'Вискозиметры'


class Kalibration(models.Model):
    dateKalib = models.DateField('Дата калибровки', auto_now_add=True)
    konstant = models.DecimalField('Установленная константа', max_digits=20, decimal_places=6, default='0')
    id_Viscosimeter = models.ForeignKey(Viscosimeters, verbose_name='Номер вискозиметра', on_delete=models.CASCADE,
                                        )
    performer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f' константа {self.konstant} к вискозиметру № {self.id_Viscosimeter.equipmentSM.equipment.lot}'

    class Meta:
        verbose_name = 'Калибровка'
        verbose_name_plural = 'Калибровки'

viscosimeters/forms.py
from django import forms
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from datetime import datetime

from django.utils.html import format_html
from .models import Kalibration, Viscosimeters
from equipment.models import Equipment


class KalibrationViscosimetersForm(forms.ModelForm):
    konstant = forms.DecimalField(label='Установленная константа', max_digits=10, decimal_places=6,  required=True,
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': 'константа через точку'}))
    id_Viscosimeter = forms.ModelChoiceField(label='Номер вискозиметра',  required=True,
                                        queryset=Viscosimeters.objects.filter(equipmentSM__equipment__status='Э'),
                                        widget=forms.Select(attrs={'class': 'form-control'}))


    class Meta:
        model = Kalibration
        fields = ['id_Viscosimeter', 'konstant']

viscosimeters/views.py
from decimal import Decimal

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.db import connection
from django.views import View
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView

from django.db.models import Max
from viscosimeters.models import*
from .forms import KalibrationViscosimetersForm


# class KalibrationViscosimetersRegView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
#     """ выводит форму внесения для внесения допинформации для формирования протокола и кнопку для протокола """
#     template_name = 'equipment/reg.html'
#     success_url = '/kalibrationviscosimetersreg/'
#     form_class = KalibrationViscosimetersForm
#
#     def form_valid(self, form):
#         order = form.save(commit=False)
#         order.performer = User.objects.get(username=self.request.user)
#         order.save()
#         return super().form_valid(form)

    # name = form.cleaned_data.get('id_Viscosimeter')
    # konstant = form.cleaned_data.get('konstant')
    # success_message = f'Константа {konstant} вискозиметра {name} внесена!'




@login_required
def KalibrationViscosimetersRegView(request):
    """ выводит форму внесения калибровки вискозиметров. """
    if request.method == "POST":
        form = KalibrationViscosimetersForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.performer = request.user
            order.save()

            return redirect('/kalibrationviscosimetersreg/')
    else:
        form = KalibrationViscosimetersForm()

    return render(
        request,
        'viscosimeters/registration.html',
        {
            'form': form
        })

class ViscosimetersView(View):
    """ Представление, которое выводит все вискозиметры с константами. """
    def get(self, request):
        get_id_actualconstant = Kalibration.objects.select_related('id_Viscosimeter').values('id_Viscosimeter').\
            annotate(id_actualkonstant=Max('id')).values('id_actualkonstant')
        list_ = list(get_id_actualconstant)
        set = []
        for n in list_:
            set.append(n.get('id_actualkonstant'))
        viscosimeters = Kalibration.objects.select_related('id_Viscosimeter').filter(id__in=set).order_by('id_Viscosimeter__viscosimeterType__diameter').\
            filter(id_Viscosimeter__equipmentSM__equipment__status = 'Э')

        data = {'viscosimeters': viscosimeters}


        return render(request, 'viscosimeters/viscosimetersKonstants.html', data)



class ViscosimetersHeadView(TemplateView):
    """ выводит заглавную старницу вискозиметров """
    template_name = 'viscosimeters/head.html'

viscosimeters/templates/viscosimeters/head.html
{% extends 'main/base.html' %}
{% load static %}
{% block uniccontent %}
    <div style="text-align: center;"><h4> Вискозиметры ВПЖ-1 </h4></div>
     <br>
         <div style="text-align: center;">
        <a href="{% url 'konstv' %}" class="btn btn-info mr-5 mt-3"> Константы вискозиметров </a>
         <a href="{% url 'kalibrationviscosimetersreg' %}" class="btn btn-info mr-5 mt-3"> Внести константу </a>
         </div>
    <br>
    <br>
    <div style="text-align: center;"><img src="{% static 'main/img/11.jpg' %}"
                                          alt="ВЖ"></div>

{% endblock %}

viscosimeters/templates/viscosimeters/registration.html
{% extends 'main/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
Внести константу
{% endblock %}


{% block content %}
    <div style="text-align: center;"><h4><a href="/viscosimeterskonstants/"> Внести константу вискозиметра </a></h4></div>
    <form method="post" class="form-register">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-warning" type="submit">Внести константу</button>
    </form>
{% endblock %}

viscosimeters/templates/viscosimeters/viscosimeterType.html
{% extends 'main/base.html' %}
{% block title %}
    Типы вискозиметров
{% endblock %}

{% block content %}
    <div style="text-align: center;"><h3>Вискозиметры ВПЖ-1</h3></div>
    <div style="text-align: center;"><h6>Межповерочный интервал 4 года</h6></div>
    <div style="text-align: center;"><h6>Госреестр: 54038-13</h6></div>
<br>

<table class="table table-bordered">

<thead>

    <tr>
      <th> <div style="text-align: center;"> № пары </div></th>
      <th> <div style="text-align: center;"> ⌀ </div></th>
      <th> <div style="text-align: center;"> Вязкость за 1000 сек, сСт </div></th>
      <th> <div style="text-align: center;"> Область измерений, сСт </div></th>
    </tr>
  </thead>

  <tbody>
{% for type in ViscosimeterTypeObjects %}

    <tr>
      <td align="center"> {{ type.pairNumber }}</td>
      <td align="center"> {{ type.diameter }}</td>
      <td align="center">{{ type.viscosity1000 }}</td>
      <td align="center">{{ type.range }}</td>
    </tr>

{% endfor %}
  </tbody>
</table>
{% endblock %}

viscosimeters/templates/viscosimeters/viscosimetersKonstants.html
{% extends 'main/base.html' %}
{% block title %}
    Вискозиметры
{% endblock %}

{% block content %}
    <div style="text-align: center;"><h3>Константы вискозиметров</h3></div>
<br>

<table class="table table-bordered">

<thead>

    <tr>
      <th> <div style="text-align: center;"> Номер </div></th>
      <th> <div style="text-align: center;"> Константа, мм<sup>2</sup>/с<sup>2</sup> </div></th>
      <th> <div style="text-align: center;"> ν/1000 </div></th>
      <th> <div style="text-align: center;"> Область измерений, мм<sup>2</sup>/с </div></th>
      <th> <div style="text-align: center;"> ⌀ </div></th>
      <th> <div style="text-align: center;"> Поверка до </div></th>
      <th> <div style="text-align: center;"> Дата калибровки </div></th>


    </tr>
  </thead>

  <tbody>
{% for note in viscosimeters %}

    <tr>
      <td> <div style="text-align: center;">
{#           {{ note.konstant }}#}
          {{ note.id_Viscosimeter.equipmentSM.equipment.lot }}
      </div></td>
      <td> <div style="text-align: center;">
{#       {{ note.kalibration_set.all.last.konstant }}#}
          {{ note.konstant|striptags }}
      </div></td>
      <td> <div style="text-align: center;"> {{ note.id_Viscosimeter.viscosimeterType.viscosity1000 }}</div></td>
      <td> <div style="text-align: center;"> {{ note.id_Viscosimeter.viscosimeterType.range }}</div></td>
      <td> <div style="text-align: center;">
{#          {{ note.viscosimeterType.diameter }}#}
          {{ note.id_Viscosimeter.viscosimeterType.diameter }}
      </div></td>
      <td> <div style="text-align: center;">  </div> {{ note.id_Viscosimeter.equipmentSM.newdatedead }}</td>
      <td> <div style="text-align: center;">
      {{ note.dateKalib|date:"d.m.Y" }}
      </div></td>

    </tr>

{% endfor %}
  </tbody>
</table>
{% endblock %}